version: "3.7"
services:
  relaychain-alice:
    ports:
      - 9947:9944
      - 9936:9933
      - 30336:30333
    volumes:
      - relaychain-alice:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local-raw.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=alice
      - --alice
      - --rpc-methods=unsafe
      - --force-authoring
    environment:
      RUST_LOG: babe=debug
    ulimits:
      &a1
      nofile:
        soft: 65536
        hard: 65536
  relaychain-bob:
    ports:
      - 9945:9944
      - 9934:9933
      - 30334:30333
    volumes:
      - relaychain-bob:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local-raw.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=bob
      - --bob
      - --rpc-methods=unsafe
    environment:
      RUST_LOG: parachain::candidate-backing=trace
    ulimits: *a1
  relaychain-charlie:
    ports:
      - 9946:9944
      - 9935:9933
      - 30335:30333
    volumes:
      - relaychain-charlie:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local-raw.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=charlie
      - --charlie
      - --rpc-methods=unsafe
    environment:
      RUST_LOG: parachain::candidate-backing=trace
    ulimits: *a1
  parachain-2000-0:
    ports:
      - 9944:9944
      - 9933:9933
      - 30333:30333
    volumes:
      - parachain-2000-0:/data
    build:
      context: .
      dockerfile: parachain-2000.Dockerfile
    command:
      - interbtc-parachain
      - --base-path=/data
      - --chain=rococo-local-2000
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2000-0
      - --collator
      - --rpc-methods=unsafe
      - --force-authoring
      - --execution=wasm
      - --alice
      - --node-key=46da5a123418935ef519945c950b6f9a75f7a54f4f024ba4825d0cefb6eac8cb
      - --listen-addr=/ip4/0.0.0.0/tcp/30333
      - --
      - --chain=/app/rococo-local-raw.json
      - --execution=wasm
      - --name=relaychain-alice
    environment:
      RUST_LOG: aura=debug
    ulimits: *a1
  parachain-2000-1:
    ports:
      - 9948:9944
      - 9937:9933
      - 30337:30333
    volumes:
      - parachain-2000-1:/data
    build:
      context: .
      dockerfile: parachain-2000.Dockerfile
    command:
      - interbtc-parachain
      - --base-path=/data
      - --chain=rococo-local-2000
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2000-1
      - --collator
      - --rpc-methods=unsafe
      - --force-authoring
      - --execution=wasm
      - --bob
      - --bootnodes=/dns/parachain-2000-0/tcp/30333/p2p/12D3KooWFiJYE2Ca8XMmEN8xKNByt8tshUFyaoHaZBnT4mww6Fsk
      - --listen-addr=/ip4/0.0.0.0/tcp/30333
      - --
      - --chain=/app/rococo-local-raw.json
      - --execution=wasm
    environment:
      RUST_LOG: sc_basic_authorship=trace
    ulimits: *a1
volumes:
  ? relaychain-alice
  ? relaychain-bob
  ? relaychain-charlie
  ? parachain-2000-0
  ? parachain-2000-1
