version: "3.7"
services:
  relaychain-alice:
    ports:
      - 9944:9944
      - 9933:9933
      - 30333:30333
    volumes:
      - relaychain-alice:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=alice
      - --alice
      - --rpc-methods=unsafe
      - --force-authoring
    environment:
      RUST_LOG: babe=debug
    ulimits:
      &a1
      nofile:
        soft: 65536
        hard: 65536
  parachain-2000-0:
    ports:
      - 9947:9944
      - 9936:9933
      - 30336:30333
    volumes:
      - parachain-2000-0:/data
    build:
      context: .
      dockerfile: parachain-2000.Dockerfile
    command:
      - interbtc-parachain
      - --base-path=/data
      - --chain=rococo-local-2000
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2000-0
      - --collator
      - --rpc-methods=unsafe
      - --force-authoring
      - --execution=wasm
      - --alice
      - --node-key=7a67ec48248ecc072a97527895a66d53e775ff23d74f7f5a83287860ae24ebca
      - --listen-addr=/ip4/0.0.0.0/tcp/30333
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
      - --name=relaychain-alice
    environment:
      RUST_LOG: aura=debug
    ulimits: *a1
  parachain-2000-1:
    ports:
      - 9946:9944
      - 9935:9933
      - 30335:30333
    volumes:
      - parachain-2000-1:/data
    build:
      context: .
      dockerfile: parachain-2000.Dockerfile
    command:
      - interbtc-parachain
      - --base-path=/data
      - --chain=rococo-local-2000
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2000-1
      - --collator
      - --rpc-methods=unsafe
      - --force-authoring
      - --execution=wasm
      - --bob
      - --bootnodes=/dns/parachain-2000-0/tcp/30333/p2p/12D3KooWMgw2vQNyxGgeKvXNt716dcNESvXXVd3ViFnCRfHdsP2B
      - --listen-addr=/ip4/0.0.0.0/tcp/30333
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
    environment:
      RUST_LOG: sc_basic_authorship=trace
    ulimits: *a1
volumes:
  ? relaychain-alice
  ? parachain-2000-0
  ? parachain-2000-1
